---

- name: Update all packages to the latest version
  apt:
    upgrade: dist
  become: yes

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: yes

- name: Install Gnome Desktop
  apt:
    name: ubuntu-desktop
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: yes
